### ISSUE TITLE
左滑前进

### ISSUE THREAD

**Issue by black1997** [PandexLee/QWWebViewFullScreenPopGesture#2]
请问一下，左滑前进该怎么改了？

**Comment by PandexLee** [comment]
1. 在 - (void)checkGestureIsAdded; 中重复一次添加self.gestureRecognizers.lastObject的action和target
2. 在38行删除if (absX > absY ) 的判断

**Comment by black1997** [comment]
在 checkGestureIsAdded中加入以下代码，并删除38行的判断，发现还是没有效果。
UIPanGestureRecognizer *originLast = self.gestureRecognizers.lastObject;
        [originLast.view addGestureRecognizer:self.qw_fullscreenPopGestureRecognizer];
        NSArray * internalLast = [originLast valueForKey:@"_targets"];
        id iternalLastTarget = [internalLast.firstObject valueForKey:@"target"];
        SEL lastAction = NSSelectorFromString(@"handleNavigationTransition:");
        if (originLast.delegate) {
            self.qw_fullscreenPopGestureRecognizer.delegate = self.qw_popGestureRecognizerDelegate;
        }
        [self.qw_fullscreenPopGestureRecognizer addTarget:iternalLastTarget action:lastAction];

**Comment by PandexLee** [comment]
试一下重新创建一个手势来接受这个target和action

**Comment by black1997** [comment]
我试了，重新加一个手势也是不行的。而且还会把原来的返回手势给覆盖掉。比价尴尬，求help

**Comment by black1997** [comment]
在38行删除if (absX > absY ) 的判断.。不加前进手势，是有左滑前进效果的。但要在屏幕最右边滑动才能前进，其他区域都是返回了。

**Comment by PandexLee** [comment]
代码已更新，默认支持全屏手势前进和后退
